name: spotify-clone

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - spotify
    depends_on:
      - mongo
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - spotify
    command: npm run dev -- --host
    depends_on:
      - backend
    ports:
      - 3000:3000
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - spotify

volumes:
  mongo_data:

networks:
  spotify:
    driver: bridge